/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package fi.jguru.yubikey.otp.login.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the YubikeyOTPKeyEntry service. Represents a row in the &quot;JGURU_YubikeyOTPKeyEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.jguru.yubikey.otp.login.service.model.impl.YubikeyOTPKeyEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.jguru.yubikey.otp.login.service.model.impl.YubikeyOTPKeyEntryImpl}.
 * </p>
 *
 * @author Mika Koivisto
 * @see YubikeyOTPKeyEntry
 * @see fi.jguru.yubikey.otp.login.service.model.impl.YubikeyOTPKeyEntryImpl
 * @see fi.jguru.yubikey.otp.login.service.model.impl.YubikeyOTPKeyEntryModelImpl
 * @generated
 */
@ProviderType
public interface YubikeyOTPKeyEntryModel extends AuditedModel,
	BaseModel<YubikeyOTPKeyEntry>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a yubikey o t p key entry model instance should use the {@link YubikeyOTPKeyEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this yubikey o t p key entry.
	 *
	 * @return the primary key of this yubikey o t p key entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this yubikey o t p key entry.
	 *
	 * @param primaryKey the primary key of this yubikey o t p key entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the key ID of this yubikey o t p key entry.
	 *
	 * @return the key ID of this yubikey o t p key entry
	 */
	public long getKeyId();

	/**
	 * Sets the key ID of this yubikey o t p key entry.
	 *
	 * @param keyId the key ID of this yubikey o t p key entry
	 */
	public void setKeyId(long keyId);

	/**
	 * Returns the company ID of this yubikey o t p key entry.
	 *
	 * @return the company ID of this yubikey o t p key entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this yubikey o t p key entry.
	 *
	 * @param companyId the company ID of this yubikey o t p key entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this yubikey o t p key entry.
	 *
	 * @return the user ID of this yubikey o t p key entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this yubikey o t p key entry.
	 *
	 * @param userId the user ID of this yubikey o t p key entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this yubikey o t p key entry.
	 *
	 * @return the user uuid of this yubikey o t p key entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this yubikey o t p key entry.
	 *
	 * @param userUuid the user uuid of this yubikey o t p key entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this yubikey o t p key entry.
	 *
	 * @return the user name of this yubikey o t p key entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this yubikey o t p key entry.
	 *
	 * @param userName the user name of this yubikey o t p key entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this yubikey o t p key entry.
	 *
	 * @return the create date of this yubikey o t p key entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this yubikey o t p key entry.
	 *
	 * @param createDate the create date of this yubikey o t p key entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this yubikey o t p key entry.
	 *
	 * @return the modified date of this yubikey o t p key entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this yubikey o t p key entry.
	 *
	 * @param modifiedDate the modified date of this yubikey o t p key entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the public ID of this yubikey o t p key entry.
	 *
	 * @return the public ID of this yubikey o t p key entry
	 */
	@AutoEscape
	public String getPublicId();

	/**
	 * Sets the public ID of this yubikey o t p key entry.
	 *
	 * @param publicId the public ID of this yubikey o t p key entry
	 */
	public void setPublicId(String publicId);

	/**
	 * Returns the name of this yubikey o t p key entry.
	 *
	 * @return the name of this yubikey o t p key entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this yubikey o t p key entry.
	 *
	 * @param name the name of this yubikey o t p key entry
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		fi.jguru.yubikey.otp.login.service.model.YubikeyOTPKeyEntry yubikeyOTPKeyEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<fi.jguru.yubikey.otp.login.service.model.YubikeyOTPKeyEntry> toCacheModel();

	@Override
	public fi.jguru.yubikey.otp.login.service.model.YubikeyOTPKeyEntry toEscapedModel();

	@Override
	public fi.jguru.yubikey.otp.login.service.model.YubikeyOTPKeyEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}